---
- name: Create Linux User
  hosts: all
  become: true
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password }}" 
        create_home: true
        shell: /bin/bash
        generate_ssh_key: true
      become: true
