---
- name: Create Linux User
  hosts: all
  become: true
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}" 
        create_home: true
        group: "{{ group }}"
        shell: /bin/bash
        generate_ssh_key: true
      become: true