---
- name: List System Group
  hosts: all
  tasks:
    - name: Get System Group List
      ansible.builtin.shell: groups
      register: groups

    - name: Show System Group List
      ansible.builtin.debug:
        var: groups.stdout
