---
- name: List System Group
  hosts: all
  tasks:
    - name: Get System Group List
      ansible.builtin.shell: "cut -d: -f1 < <(getent group)"
      args:
        executable: /bin/bash
      register: result

    - name: Show System Group List
      ansible.builtin.debug:
        var: result.stdout