---
- name: List System Users
  hosts: all
  tasks:
    - name: Get System Users List
      ansible.builtin.getent:
        database: passwd
      register: users

    - name: Show System Users List
      ansible.builtin.debug:
        var: users.ansible_facts.getent_passwd