---
- name: List System Group
  hosts: all
  tasks:
    - name: Get System Group List
      ansible.builtin.getent:
        database: group
      register: groups

    - name: Show System Group List
      ansible.builtin.debug:
        var: groups.ansible_facts.getent_group
