---
- name: List System Users
  hosts: all
  tasks:
    - name: List all users
      ansible.builtin.shell: "cut -d: -f1 < <(getent passwd)"
      args:
        executable: /bin/bash
      register: users

    - name: Show System Users List
      ansible.builtin.debug:
        var: users.stdout